spring.application.name=SmartPublicTransportPlanner

# to check sql queries
spring.jpa.show-sql=true

# connecting sql with spring
spring.datasource.url=jdbc:mysql://localhost:3306/smartpublictransportplanner
spring.datasource.username=root
spring.datasource.password=Mayuresh@57223
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
